# Form implementation generated from reading ui file 'Project2.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 240)
        MainWindow.setMaximumSize(QtCore.QSize(200, 240))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.John = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.John.setGeometry(QtCore.QRect(40, 60, 62, 21))
        self.John.setObjectName("John")
        self.Candidates = QtWidgets.QButtonGroup(MainWindow)
        self.Candidates.setObjectName("Candidates")
        self.Candidates.addButton(self.John)
        self.Jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Jane.setGeometry(QtCore.QRect(40, 100, 62, 21))
        self.Jane.setObjectName("Jane")
        self.Candidates.addButton(self.Jane)
        self.Vote_ID = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Vote_ID.setGeometry(QtCore.QRect(60, 10, 121, 21))
        self.Vote_ID.setObjectName("Vote_ID")
        self.Fill_In_Text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Fill_In_Text.setGeometry(QtCore.QRect(60, 140, 104, 21))
        self.Fill_In_Text.setObjectName("Fill_In_Text")
        self.Fill_In_Button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Fill_In_Button.setGeometry(QtCore.QRect(40, 140, 21, 21))
        self.Fill_In_Button.setText("")
        self.Fill_In_Button.setObjectName("Fill_In_Button")
        self.Candidates.addButton(self.Fill_In_Button)
        self.save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save.setGeometry(QtCore.QRect(70, 180, 56, 17))
        self.save.setObjectName("save")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 191, 20))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.label.setObjectName("label")
        self.Submitted_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Submitted_Label.setGeometry(QtCore.QRect(10, 199, 181, 21))
        self.Submitted_Label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Submitted_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Submitted_Label.setObjectName("Submitted_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.John.setText(_translate("MainWindow", "John"))
        self.Jane.setText(_translate("MainWindow", "Jane"))
        self.save.setText(_translate("MainWindow", "Submit"))
        self.label_2.setText(_translate("MainWindow", "Choose or Write in Candidate"))
        self.label.setText(_translate("MainWindow", "Voter ID"))
        self.Submitted_Label.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
